/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DialoguesRouteImport } from './routes/dialogues'
import { Route as ErrorsRouteImport } from './routes/errors'
import { Route as GeminiRouteImport } from './routes/gemini'
import { Route as LessonsRouteImport } from './routes/lessons'
import { Route as LevelsRouteImport } from './routes/levels'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RulesRouteImport } from './routes/rules'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DialoguesRoute = DialoguesRouteImport.update({
  id: '/dialogues',
  path: '/dialogues',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/errors',
  path: '/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const GeminiRoute = GeminiRouteImport.update({
  id: '/gemini',
  path: '/gemini',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsRoute = LessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsRoute = LevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dialogues': typeof DialoguesRoute
  '/errors': typeof ErrorsRoute
  '/gemini': typeof GeminiRoute
  '/lessons': typeof LessonsRoute
  '/levels': typeof LevelsRoute
  '/placement': typeof PlacementRoute
  '/reviews': typeof ReviewsRoute
  '/rules': typeof RulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dialogues': typeof DialoguesRoute
  '/errors': typeof ErrorsRoute
  '/gemini': typeof GeminiRoute
  '/lessons': typeof LessonsRoute
  '/levels': typeof LevelsRoute
  '/placement': typeof PlacementRoute
  '/reviews': typeof ReviewsRoute
  '/rules': typeof RulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dialogues': typeof DialoguesRoute
  '/errors': typeof ErrorsRoute
  '/gemini': typeof GeminiRoute
  '/lessons': typeof LessonsRoute
  '/levels': typeof LevelsRoute
  '/placement': typeof PlacementRoute
  '/reviews': typeof ReviewsRoute
  '/rules': typeof RulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dialogues'
    | '/errors'
    | '/gemini'
    | '/lessons'
    | '/levels'
    | '/placement'
    | '/reviews'
    | '/rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dialogues'
    | '/errors'
    | '/gemini'
    | '/lessons'
    | '/levels'
    | '/placement'
    | '/reviews'
    | '/rules'
  id:
    | '__root__'
    | '/'
    | '/dialogues'
    | '/errors'
    | '/gemini'
    | '/lessons'
    | '/levels'
    | '/placement'
    | '/reviews'
    | '/rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DialoguesRoute: typeof DialoguesRoute
  ErrorsRoute: typeof ErrorsRoute
  GeminiRoute: typeof GeminiRoute
  LessonsRoute: typeof LessonsRoute
  LevelsRoute: typeof LevelsRoute
  PlacementRoute: typeof PlacementRoute
  ReviewsRoute: typeof ReviewsRoute
  RulesRoute: typeof RulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dialogues': {
      id: '/dialogues'
      path: '/dialogues'
      fullPath: '/dialogues'
      preLoaderRoute: typeof DialoguesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors': {
      id: '/errors'
      path: '/errors'
      fullPath: '/errors'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gemini': {
      id: '/gemini'
      path: '/gemini'
      fullPath: '/gemini'
      preLoaderRoute: typeof GeminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons': {
      id: '/lessons'
      path: '/lessons'
      fullPath: '/lessons'
      preLoaderRoute: typeof LessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels': {
      id: '/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DialoguesRoute: DialoguesRoute,
  ErrorsRoute: ErrorsRoute,
  GeminiRoute: GeminiRoute,
  LessonsRoute: LessonsRoute,
  LevelsRoute: LevelsRoute,
  PlacementRoute: PlacementRoute,
  ReviewsRoute: ReviewsRoute,
  RulesRoute: RulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
